### ISSUE TITLE
JVM Settings

### ISSUE THREAD

**Issue by qrpike** [Yolean/kubernetes-kafka#112]
Since using a JVM in containers is already somewhat scary, setting limits on the pods is always a good idea, however there are no mentions of this in the docs. 

Adding a:
```
        env:
        - name: "KAFKA_HEAP_OPTS"
          value: "-Xmx6G -Xms6G"
        resources:
          limits:
            cpu: 4
            memory: 8G
```

In the docs may be a good idea. JVMs tend to consume memory unless told otherwise.
