### ISSUE TITLE
Using local storage on SAN

### ISSUE THREAD

**Issue by EricVS** [Yolean/kubernetes-kafka#127]
Hi, 
I'm new to Kubernetes so hope this doesn't cause a problem for you, if so, please let me know.
I am using your template to setup Zookeeper/Kafka on our own Kubernetes environment and modified it in such a way that data and config write to local disk on the host (LUN presented to all 6 hosts). 
When I 'apply' the Stateful Sets for pzoo, zoo and kafka, I see that directories are created correctly, but no config files (configMag) are generated, hence the containers fail to start with error: Back-off restarting failed container.

The error in the docker logs : /bin/bash: /etc/kafka/init.sh: No such file or directory

Any clue on what I might be doing wrong? This is what I modified:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-zookeeper-config
  labels:
    type: local
spec:
  storageClassName: zookeeper-config
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/kubernetes/zk/config"

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-config-claim
spec:
  storageClassName: zookeeper-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

in 50pzoo.yml:

      volumes:
      - name: config
        configMap:
          name: zookeeper-config
        persistentVolumeClaim:
          claimName: zookeeper-config-claim
      - name: data
        persistentVolumeClaim:
          claimName: zookeeper-data-claim
```

Any help is highly appreciated.

Kind regards, 

Eric V.

**Comment by solsson** [comment]
Is the configmap mount https://github.com/Yolean/kubernetes-kafka/blob/v3.0.1/kafka/50kafka.yml#L73 still present after your changes? `/bin/bash: /etc/kafka/init.sh: No such file or directory` indicates that it's not.

How you provision your other volumes is probably unrelated, but I'm curious if you're using [local volumes](https://kubernetes.io/docs/concepts/storage/volumes/#local)? I tested that with K8s 1.9 in https://github.com/Yolean/kubeadm-vagrant/commit/ee897eac606cff77c4dea008717035d75e3335c1.

**Comment by EricVS** [comment]
Thanks for your reply! 
Yes it is still present:
```
        volumeMounts:
        - name: config
          mountPath: /etc/kafka
        - name: data
          mountPath: /var/lib/kafka/data
```
I am using a LUN presented to all six nodes in my cluster, mounted under /kubernetes. 
I'm trying to get familiar with as many layers of Kubernetes as possible but the learning curve is pretty steep :-). I'm running K8S 1.8.3 on Rancher.

Kind regards, 

Eric V.
