### ISSUE TITLE
kafka-broker-id labels could be simplified with 1.9 statefulset.kubernetes.io/pod-name

### ISSUE THREAD

**Issue by golonzovsky** [Yolean/kubernetes-kafka#196]
From 1.9 kubernetes adds statefulset pod labels by itself, e.g. `statefulset.kubernetes.io/pod-name=kafka-0` (see [docks change](https://github.com/kubernetes/website/blame/master/content/en/docs/concepts/workloads/controllers/statefulset.md#L160-L164))

Maybe [pod labeler logic](https://github.com/Yolean/kubernetes-kafka/blob/master/kafka/10broker-config.yml#L14) could be simplified

Outside service could look like:
```
kind: Service
apiVersion: v1
metadata:
  name: outside-0
  namespace: kafka
spec:
  selector:
    app: kafka
    statefulset.kubernetes.io/pod-name: kafka-0
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 32400
    nodePort: 32400
  type: NodePort
```
