### ISSUE TITLE
Kafka init container not starting up

### ISSUE THREAD

**Issue by omkardeshpande8** [Yolean/kubernetes-kafka#236]
Hello,

I am using master branch of this repo. I am using aws-storageclasses. And I have made following changes - 

51zoo.yml
```
-      storageClassName: kafka-zookeeper-regional
+     storageClassName: kafka-zookeeper
```

50kafka.yml
```
-          storage: 10Gi
+          storage: 1Gi
```

The zookeeper pods are in running state.

The kafka init container is failing. The only error message I can see in the logs-

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-01-09T08:21:14Z
    message: 'containers with incomplete status: [init-config]'
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-01-09T08:21:14Z
    message: 'containers with unready status: [broker]'
    reason: ContainersNotReady
    status: "False"
    type: Ready

```

  ```
initContainerStatuses:
  - containerID: docker://1b5b4d09b304c1463f0d50088d79556c93adea745e96d71506349529e63be473
    image: sha256:5f8f891eada9aa93d4acd5b6493210216e8af291ab549814e55dc6bebcbf4cad
    imageID: docker-pullable://solsson/kafka-initutils@sha256:2cdb90ea514194d541c7b869ac15d2d530ca64889f56e270161fe4e5c3d076ea
    lastState:
      terminated:
        containerID: docker://1b5b4d09b304c1463f0d50088d79556c93adea745e96d71506349529e63be473
        exitCode: 1
        finishedAt: 2019-01-09T08:23:00Z
        reason: Error
        startedAt: 2019-01-09T08:23:00Z
    name: init-config
    ready: false
    restartCount: 4
    state:
      waiting:
        message: Back-off 1m20s restarting failed container=init-config pod=kafka-0_kafka(87c31197-13e7-11e9-b8f9-0646a20e6d00)
        reason: CrashLoopBackOff

```

Any thoughts on this?
