### ISSUE TITLE
How to do dyanmic PVC claim ?

### ISSUE THREAD

**Issue by HackToHell** [Yolean/kubernetes-kafka#25]
Added 

```yaml
  volumeClaimTemplates:
  - metadata:
      name: datadir
      annotations:
          volume.beta.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 8Gi
```
to the `50kafka.yml` file and commented out the `10pvc.yaml` file but still getting an error saying 
```
[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-kafka-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-kafka-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-kafka-0", which is unexpected.]
```
I am unable to solve this particular issue, do you have any idea what I am doing wrong.
