### ISSUE TITLE
Zookeeper persistent data?

### ISSUE THREAD

**Issue by gytisgreitai** [Yolean/kubernetes-kafka#26]
Hi,

from the Readme: 
> Zookeeper runs as a Deployment without persistent storage:

but looking at zookeeper it looks like you are using stateful set with local storage. Maybe I'm missing something, but I could probably use same persistent storage approach as with kafka, eg:
```
<snip>
          volumeMounts:
            - name: zookeeper-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
        annotations:
          volume.beta.kubernetes.io/storage-class: slow
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500m
<snip>
```

Haven't tested much, but seems to be working?
