### ISSUE TITLE
Issues with provisioning PVC

### ISSUE THREAD

**Issue by cdelpinogeo** [Yolean/kubernetes-kafka#27]
Hello,

Trying to deploy kafka on Kubernetes running on aws. I am using EFS on the storage end. Here is what I have for defining the PV:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-api-pers-kafka-0
  labels:
    app: api-pers-kafka
    podindex: "0"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  nfs:
    path: /efsfileshare/datadir-kafka-0
    server: EFS URL
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-api-pers-kafka-1
  labels:
    app: api-pers-kafka
    podindex: "1"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  nfs:
    path: /efsfileshare/datadir-kafka-1
    server: EFS URL
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-api-pers-kafka-2
  labels:
    app: api-pers-kafka
    podindex: "2"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  nfs:
    path: /efsfileshare/datadir-kafka-2
    server: EFS URL
```
here is what i have for pvc:

```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-api-pers-kafka-0
  namespace: capi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      app: kafka
      podindex: "0"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-api-pers-kafka-1
  namespace: capi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      app: kafka
      podindex: "1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-api-pers-kafka-2
  namespace: capi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  selector:
    matchLabels:
      app: kafka
      podindex: "2"
```
The PV's look to deploy fine, but the PVC's are stuck in a pending status. When I deploy the statefulset manifest, I get the following error:

```
[SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-api-pers-kafka-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-api-pers-kafka-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-api-pers-kafka-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-api-pers-kafka-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-api-pers-kafka-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-api-pers-kafka-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-api-pers-kafka-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-api-pers-kafka-0", which is unexpected., SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "datadir-api-pers-kafka-0", which is unexpected.]
```
Here is the manifest for the statefulset:

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: api-pers-kafka
  namespace: capi
spec:
  serviceName: "api-pers-broker"
  replicas: 3
  template:
    metadata:
      labels:
        app: api-pers-kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: api-pers-broker
        image: solsson/kafka-persistent
        ports:
        - containerPort: 9092
        command:
        - sh
        - -c
        - "./bin/kafka-server-start.sh config/server.properties --override broker.id=$(hostname | awk -F'-' '{print $2}')"
        volumeMounts:
        - name: datadir
          mountPath: /opt/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 200Gi
```
Not sure what needs correcting. Thanks!
