### ISSUE TITLE
Running on kubernetes cluster 1.6.2 fails

### ISSUE THREAD

**Issue by cairesvs** [Yolean/kubernetes-kafka#64]
I'm running on already establish cluster (1.6.2) but it fails the `kubectl apply -f ./zookeper` and afterwards fails on `kubectl apply -f ./`.

Seems like the initContainer isn't running so I changed to for the zookeeper:
```yaml
annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "init-config",
                "image": "solsson/kafka:0.11.0.0@sha256:b27560de08d30ebf96d12e74f80afcaca503ad4ca3103e63b1fd43a2e4c976ce",
                "command": ["/bin/bash", "/etc/kafka/init.sh"],
                "volumeMounts": [
                    {
                      "name": "config",
                      "mountPath": "/etc/kafka"
                    },
                    {
                      "name": "data",
                      "mountPath": "/var/lib/zookeeper/data"
                    }
                ]
            }
        ]'
```

But for 50kafka.yml because of `spec.nodeName`
```yaml
initContainers:
      - name: init-config
        image: solsson/kafka-initutils@sha256:c275d681019a0d8f01295dbd4a5bae3cfa945c8d0f7f685ae1f00f2579f08c7d
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command: ['/bin/bash', '/etc/kafka/init.sh']
```

I can't use the same approach.

There's something missing?

Cheers
